<?php

declare(strict_types=1);

return [
    'company' => [
        'name' => 'Digi CNC',
        'brand' => 'Digi CNC Nagpur - 2D & 3D CNC Cutting & Carving',
        'founder' => 'Mr. Krunal Patel',
        'experience' => '5+ Years',
        'phone' => '+91 9766653376',
        'whatsapp' => '+91 9766653376',
        'location' => 'Plot no.11 Bharatwada Rd, Bharatwada, Nagpur, Maharashtra 440035',
        'hours' => 'Monday to Saturday, 9:30 AM to 7:00 PM',
        'tagline' => 'Precision CNC cutting, carving, engraving, jali, furniture components, prototypes, and parametric manufacturing for architects, designers, manufacturers, and homeowners.',
    ],
    'stats' => [
        ['value' => 5, 'suffix' => '+', 'label' => 'Years CNC Experience'],
        ['value' => 900, 'suffix' => '+', 'label' => 'Panels & Components Delivered'],
        ['value' => 30, 'suffix' => '+', 'label' => 'Material/Finish Use Cases'],
        ['value' => 100, 'suffix' => '%', 'label' => 'Custom Project Focus'],
    ],
    'hero_slides' => [
        [
            'eyebrow' => 'Digi CNC Nagpur - Precision CNC Manufacturing',
            'title' => 'Premium CNC Cutting, Carving, Jali and Parametric Manufacturing in Nagpur',
            'copy' => 'Digi CNC helps architects, interior designers, furniture manufacturers and homeowners convert drawings into clean CNC-manufactured parts with reliable accuracy, finishing sense and production discipline.',
            'image' => 'assets/images/hero-slider-jali-cnc-clean.png',
            'alt' => 'Premium CNC jali cutting in Nagpur by Digi CNC',
        ],
        [
            'eyebrow' => 'Parametric Design Manufacturing',
            'title' => 'Design-led CNC panels, ribs and feature walls built for real installation.',
            'copy' => 'From parametric wall systems to decorative partitions and premium commercial interiors, Digi CNC turns digital geometry into organized, CNC-ready components.',
            'image' => 'assets/images/hero-slider-parametric-wall-clean.png',
            'alt' => 'Parametric CNC wall panel manufacturing in Nagpur',
        ],
        [
            'eyebrow' => 'Furniture Components & Prototypes',
            'title' => 'Repeatable MDF, HDHMR, acrylic and plywood components for serious projects.',
            'copy' => 'Use Digi CNC for furniture components, prototype samples, ACP, WPC, acrylic, engraving and custom sheet-material work where accuracy and communication matter.',
            'image' => 'assets/images/hero-slider-components-prototype-clean.png',
            'alt' => 'CNC furniture components and prototype manufacturing by Digi CNC',
        ],
    ],
    'materials' => [
        'MDF',
        'HDHMR',
        'Natural Wood',
        'Acrylic',
        'PVC',
        'ACP',
        'WPC',
        'Plywood',
        'Decorative Laminates',
    ],
    'industries' => [
        'Architects',
        'Interior Designers',
        'Furniture Manufacturers',
        'Furniture Contractors',
        'Industrial Manufacturers',
        'Artists',
        'Prototype Development Companies',
        'Homeowners',
        'Renovation Projects',
        'Commercial Projects',
    ],
    'services' => [
        [
            'name' => '2D CNC Cutting',
            'slug' => '2d-cnc-cutting-nagpur',
            'summary' => 'Accurate profile cutting, nesting, slots, perforations, furniture parts, signage bases, and repeatable panel components.',
            'icon' => 'square-dashed',
            'image' => 'assets/images/banner-about-process-clean.png',
        ],
        [
            'name' => '3D CNC Carving',
            'slug' => '3d-cnc-carving-nagpur',
            'summary' => 'Relief carving, decorative panels, textured wall surfaces, custom motifs, and sculptural wooden elements with refined finish planning.',
            'icon' => 'layers',
            'image' => 'assets/images/portfolio-3d-carving.png',
        ],
        [
            'name' => 'Parametric Design Manufacturing',
            'slug' => 'parametric-design-nagpur',
            'summary' => 'Manufacturing support for algorithmic facades, ribs, baffles, wave panels, retail installations, and design-led interiors.',
            'icon' => 'wave',
            'image' => 'assets/images/hero-slider-parametric-wall-clean.png',
        ],
        [
            'name' => 'Decorative Jali Cutting',
            'slug' => 'decorative-jali-cutting-nagpur',
            'summary' => 'Premium CNC jali screens for partitions, mandirs, wall panels, doors, ceilings, commercial branding, and residential features.',
            'icon' => 'grid',
            'image' => 'assets/images/hero-slider-jali-cnc-clean.png',
        ],
        [
            'name' => 'MDF CNC Cutting',
            'slug' => 'mdf-cnc-cutting-nagpur',
            'summary' => 'Optimized MDF cutting for panels, cabinetry, wall features, display units, CNC mandir elements, and decorative profiles.',
            'icon' => 'box',
            'image' => 'assets/images/hero-slider-components-prototype-clean.png',
        ],
        [
            'name' => 'HDHMR CNC Cutting',
            'slug' => 'hdhmr-cnc-cutting-nagpur',
            'summary' => 'Precision HDHMR routing for high-moisture-resistance furniture, kitchens, wardrobes, shutters, and interior components.',
            'icon' => 'shield',
            'image' => 'assets/images/hero-slider-components-prototype-clean.png',
        ],
        [
            'name' => 'Custom CNC Projects',
            'slug' => 'custom-cnc-projects',
            'summary' => 'Prototype development, bespoke engraving, furniture components, acrylic, ACP, WPC, plywood, and mixed-material CNC work.',
            'icon' => 'spark',
            'image' => 'assets/images/banner-services-materials-clean.png',
        ],
        [
            'name' => 'Furniture Components Manufacturing',
            'slug' => 'services',
            'summary' => 'Repeatable CNC-ready parts for contractors, modular furniture teams, retail display makers, and fabrication workshops.',
            'icon' => 'chair',
            'image' => 'assets/images/hero-slider-components-prototype-clean.png',
        ],
        [
            'name' => 'CNC Engraving',
            'slug' => 'services',
            'summary' => 'Sharp engraved branding, numbering, decorative detail, surface textures, and custom pattern work on suitable sheet materials.',
            'icon' => 'pen',
            'image' => 'assets/images/banner-about-process-clean.png',
        ],
        [
            'name' => 'Mandir Designs',
            'slug' => 'decorative-jali-cutting-nagpur',
            'summary' => 'Detailed CNC mandir panels, arches, backdrops, doors, jaalis, and customized spiritual interior elements.',
            'icon' => 'arch',
            'image' => 'assets/images/portfolio-jali-mandir.png',
        ],
    ],
    'service_pages' => [
        'CNC-cutting-service-nagpur' => [
            'title' => 'CNC Cutting Service in Nagpur',
            'h1' => 'CNC Cutting Service in Nagpur for Premium Interiors, Furniture, Jali and Industrial Parts',
            'keyword' => 'CNC Cutting Service in Nagpur',
            'meta_description' => 'Digi CNC offers precision CNC cutting service in Nagpur for MDF, HDHMR, acrylic, ACP, WPC, plywood, jali, furniture components and custom projects.',
            'image' => 'assets/images/hero-slider-jali-cnc-clean.png',
            'summary' => 'Digi CNC provides a reliable CNC cutting service in Nagpur for businesses and homeowners who need clean edges, accurate dimensions, repeatable production, and a practical manufacturing partner who can understand drawings as well as site realities.',
            'applications' => ['Interior partitions', 'Furniture parts', 'Retail displays', 'Industrial templates', 'Architectural panels', 'Prototype parts'],
            'materials' => ['MDF', 'HDHMR', 'Plywood', 'Acrylic', 'ACP', 'PVC', 'WPC'],
            'differentiators' => ['Drawing review before cutting', 'Material-aware feed and tool planning', 'Clean nesting for lower wastage', 'Responsive support from Nagpur'],
            'faqs' => [
                ['q' => 'Do you provide CNC cutting for single custom pieces?', 'a' => 'Yes. Digi CNC works on one-off custom pieces, sample panels, prototype parts, and larger repeat production batches. The process begins with drawing review and material confirmation.'],
                ['q' => 'Which file formats are preferred for CNC cutting?', 'a' => 'DXF, DWG, AI, CDR, SVG and clean PDF references are commonly used. If the file is not production-ready, the team can help review and prepare it for CNC machining.'],
                ['q' => 'Can you cut furniture components in bulk?', 'a' => 'Yes. We support contractors and furniture manufacturers with repeatable CNC-cut parts, nesting, component labelling, and production planning for MDF, HDHMR, plywood and similar sheet materials.'],
                ['q' => 'Do you serve customers outside Nagpur?', 'a' => 'Yes. Digi CNC serves Nagpur and project requirements across Maharashtra depending on material, drawing, quantity, logistics and delivery feasibility.'],
            ],
        ],
        '3d-cnc-carving-nagpur' => [
            'title' => '3D CNC Carving Nagpur',
            'h1' => '3D CNC Carving in Nagpur for Decorative Wood, Wall Panels and Custom Relief Work',
            'keyword' => '3D CNC Carving Nagpur',
            'meta_description' => 'Premium 3D CNC carving in Nagpur for wood, MDF, decorative wall panels, carved doors, relief art, mandir elements and interior design features.',
            'image' => 'assets/images/portfolio-3d-carving.png',
            'summary' => 'Digi CNC creates 3D carved surfaces where depth, texture and detail need to feel intentional. The service is suited to interior designers, architects, artists, furniture makers and homeowners who want carved panels that look crafted, not mass-produced.',
            'applications' => ['3D wall panels', 'Carved doors', 'Mandir panels', 'Art panels', 'Logo reliefs', 'Luxury furniture inserts'],
            'materials' => ['Wood', 'MDF', 'HDHMR', 'Plywood'],
            'differentiators' => ['Toolpath planning for relief depth', 'Fine finishing allowance', 'Pattern scaling support', 'Premium carved detail'],
            'faqs' => [
                ['q' => 'Can you carve custom 3D designs?', 'a' => 'Yes. Custom motifs, textures, relief panels, brand elements, mandir features and artistic panels can be machined after reviewing design depth, material thickness and finish expectations.'],
                ['q' => 'Which material gives the best 3D carving finish?', 'a' => 'Natural wood is excellent for premium carving when grain and finish matter. MDF and HDHMR are strong options for painted panels and consistent decorative relief work.'],
                ['q' => 'Can you create a 3D file from a reference image?', 'a' => 'For many projects, a reference image can be converted into a production-ready carving model or toolpath after scope review. Complex sculptural work may need dedicated modeling time.'],
                ['q' => 'Is 3D carving suitable for commercial interiors?', 'a' => 'Yes. 3D CNC carving is widely used for reception walls, restaurant interiors, hotel panels, showroom features, retail displays and premium office spaces.'],
            ],
        ],
        '2d-cnc-cutting-nagpur' => [
            'title' => '2D CNC Cutting Nagpur',
            'h1' => '2D CNC Cutting in Nagpur for Panels, Profiles, Furniture Parts and Production Components',
            'keyword' => '2D CNC Cutting Nagpur',
            'meta_description' => 'Accurate 2D CNC cutting in Nagpur for MDF, HDHMR, plywood, acrylic, ACP, WPC, PVC, furniture parts, signage, jali and custom profiles.',
            'image' => 'assets/images/banner-about-process-clean.png',
            'summary' => 'Digi CNC handles flat-sheet CNC work where accuracy, repeatability and clean profiles are essential. From cabinet parts and retail fixtures to acrylic signage bases and perforated screens, 2D cutting helps turn digital drawings into production-ready components.',
            'applications' => ['Nested furniture parts', 'Cabinet shutters', 'Signage bases', 'Acrylic profiles', 'ACP panels', 'Template cutting'],
            'materials' => ['MDF', 'HDHMR', 'Plywood', 'Acrylic', 'ACP', 'PVC', 'WPC'],
            'differentiators' => ['Repeatable dimensions', 'Optimized sheet nesting', 'Clean edge routing', 'Prototype-to-production support'],
            'faqs' => [
                ['q' => 'Is 2D CNC cutting good for furniture manufacturing?', 'a' => 'Yes. It is ideal for repeatable furniture components, cabinet parts, shelves, grooves, drilling references, doors, panels and modular furniture elements.'],
                ['q' => 'Can you cut acrylic and ACP?', 'a' => 'Yes. Digi CNC works with acrylic, ACP and other sheet materials after confirming thickness, finish, tool suitability and edge quality expectations.'],
                ['q' => 'Can you help reduce material wastage?', 'a' => 'Yes. Proper nesting can improve sheet usage and reduce wastage, especially for repeated furniture and panel cutting jobs.'],
                ['q' => 'Do you provide urgent CNC cutting in Nagpur?', 'a' => 'Urgent work can be considered depending on file readiness, material availability and current production schedule. Calling or WhatsApp is fastest for urgent requests.'],
            ],
        ],
        'parametric-design-nagpur' => [
            'title' => 'Parametric Design Nagpur',
            'h1' => 'Parametric Design Manufacturing in Nagpur for Wave Panels, Facades, Ribs and Design-Led Interiors',
            'keyword' => 'Parametric Design Nagpur',
            'meta_description' => 'Digi CNC manufactures parametric design elements in Nagpur including wave panels, rib walls, baffles, feature ceilings, partitions and architectural installations.',
            'image' => 'assets/images/hero-slider-parametric-wall-clean.png',
            'summary' => 'Parametric design becomes valuable only when digital geometry can be manufactured accurately. Digi CNC helps designers, architects and contractors translate algorithmic forms into CNC-ready parts with sensible tolerances, material logic and installation thinking.',
            'applications' => ['Parametric wall panels', 'Ceiling baffles', 'Ribbed partitions', 'Retail installations', 'Facade prototypes', 'Feature furniture'],
            'materials' => ['MDF', 'HDHMR', 'Plywood', 'WPC', 'Acrylic'],
            'differentiators' => ['Part numbering strategy', 'Manufacturing-friendly geometry', 'Assembly-aware planning', 'Prototype before batch production'],
            'faqs' => [
                ['q' => 'Can you manufacture parametric designs from Rhino or Grasshopper files?', 'a' => 'Yes. Manufacturing can be planned from clean exported profiles and drawings. Files are reviewed for part thickness, joint strategy, numbering and cutting feasibility.'],
                ['q' => 'Are parametric panels expensive?', 'a' => 'Cost depends on material, sheet usage, number of unique parts, machining time, finishing and installation complexity. Digi CNC helps simplify geometry where possible without weakening the design intent.'],
                ['q' => 'Can you make a small sample before final production?', 'a' => 'Yes. A sample or prototype is recommended for complex parametric installations because it confirms scale, spacing, material behavior and assembly method.'],
                ['q' => 'Do you install parametric work?', 'a' => 'Digi CNC primarily manufactures CNC components and can coordinate with contractors, designers and site teams for installation planning depending on project scope.'],
            ],
        ],
        'decorative-jali-cutting-nagpur' => [
            'title' => 'Decorative Jali Cutting Nagpur',
            'h1' => 'Decorative Jali Cutting in Nagpur for Partitions, Mandirs, Doors and Premium Wall Panels',
            'keyword' => 'Decorative Jali Cutting Nagpur',
            'meta_description' => 'Decorative jali cutting in Nagpur for MDF, HDHMR, wood, WPC, PVC and acrylic partitions, mandir designs, screens, wall panels and interior features.',
            'image' => 'assets/images/hero-slider-jali-cnc-clean.png',
            'summary' => 'Digi CNC cuts decorative jali panels that combine design clarity with strong manufacturing sense. The service is widely used for residential interiors, commercial spaces, mandir units, partitions, wall panels, door inserts and branded design features.',
            'applications' => ['Mandir jaalis', 'Room partitions', 'Door inserts', 'Ceiling panels', 'Feature walls', 'Commercial screens'],
            'materials' => ['MDF', 'HDHMR', 'Wood', 'PVC', 'WPC', 'Acrylic'],
            'differentiators' => ['Pattern scaling guidance', 'Clean inside corners', 'Strength-aware web thickness', 'Design library plus custom patterns'],
            'faqs' => [
                ['q' => 'Which material is best for decorative jali?', 'a' => 'MDF is popular for painted interiors, HDHMR is preferred where moisture resistance matters, wood offers a premium natural finish, and acrylic or PVC can suit specialty design needs.'],
                ['q' => 'Can you make custom mandir jali designs?', 'a' => 'Yes. Digi CNC can create custom mandir panels, arches, backdrops, doors and decorative screens based on dimensions, references and material choice.'],
                ['q' => 'Will thin jali patterns break?', 'a' => 'Thin patterns can become fragile. Digi CNC reviews web thickness, panel size and material before cutting so the final jali balances beauty, strength and usability.'],
                ['q' => 'Can jali panels be painted or laminated?', 'a' => 'Yes. Many CNC jali panels are finished with paint, polish, laminate, veneer or specialty coatings depending on material and design intent.'],
            ],
        ],
        'mdf-cnc-cutting-nagpur' => [
            'title' => 'MDF CNC Cutting Nagpur',
            'h1' => 'MDF CNC Cutting in Nagpur for Interior Panels, Furniture, Jali, Mandir and Decorative Work',
            'keyword' => 'MDF CNC Cutting',
            'meta_description' => 'MDF CNC cutting in Nagpur for decorative jali, furniture components, wall panels, mandir designs, profiles, grooves and custom interior projects.',
            'image' => 'assets/images/hero-slider-components-prototype-clean.png',
            'summary' => 'MDF remains one of the most useful materials for CNC interior work because it cuts cleanly, paints well and supports a wide range of decorative profiles. Digi CNC helps clients convert MDF sheets into accurate panels, components and design-led features.',
            'applications' => ['Painted wall panels', 'Mandir elements', 'Furniture parts', 'Retail displays', 'Jali panels', 'Decorative grooves'],
            'materials' => ['MDF'],
            'differentiators' => ['Paint-ready machining approach', 'Panel layout planning', 'Clean decorative profiles', 'Repeatable batch cutting'],
            'faqs' => [
                ['q' => 'What thickness of MDF can be cut?', 'a' => 'Common MDF thicknesses can be processed depending on design, tool reach and finish requirement. Share the thickness and drawing for accurate confirmation.'],
                ['q' => 'Is MDF suitable for 3D carving?', 'a' => 'Yes. MDF is suitable for many painted 3D carved panels and decorative relief designs because it offers a consistent surface and predictable machining behavior.'],
                ['q' => 'Can you cut MDF mandir designs?', 'a' => 'Yes. MDF mandir panels, arches, doors, jaalis, back panels and decorative profiles are common CNC applications.'],
                ['q' => 'Do you help with MDF design files?', 'a' => 'Yes. Digi CNC can review and prepare production-ready files when dimensions, references and material details are provided.'],
            ],
        ],
        'hdhmr-cnc-cutting-nagpur' => [
            'title' => 'HDHMR CNC Cutting Nagpur',
            'h1' => 'HDHMR CNC Cutting in Nagpur for Kitchens, Wardrobes, Furniture and Moisture-Resistant Interiors',
            'keyword' => 'HDHMR CNC Cutting',
            'meta_description' => 'HDHMR CNC cutting in Nagpur for kitchens, wardrobes, shutters, modular furniture, wall panels and premium interior projects requiring durable sheet material.',
            'image' => 'assets/images/hero-slider-components-prototype-clean.png',
            'summary' => 'HDHMR is preferred by many furniture and interior teams because it offers strength and better moisture resistance than ordinary MDF. Digi CNC cuts HDHMR for kitchens, wardrobes, shutters, panels, partitions and design components that need dependable performance.',
            'applications' => ['Kitchen shutters', 'Wardrobe components', 'Bathroom-adjacent furniture', 'Retail counters', 'Durable jali panels', 'Commercial interiors'],
            'materials' => ['HDHMR'],
            'differentiators' => ['Moisture-aware application planning', 'Precise drilling and routing references', 'Batch component consistency', 'Contractor-friendly production support'],
            'faqs' => [
                ['q' => 'Is HDHMR better than MDF?', 'a' => 'HDHMR is denser and more moisture-resistant, so it is often preferred for kitchens, wardrobes, commercial furniture and areas where durability matters. MDF remains useful for many painted decorative applications.'],
                ['q' => 'Can HDHMR be used for jali?', 'a' => 'Yes. HDHMR can be used for decorative jali when the pattern thickness, panel size and finish requirement are planned properly.'],
                ['q' => 'Do you cut HDHMR for modular furniture manufacturers?', 'a' => 'Yes. Digi CNC supports modular furniture teams and contractors with repeatable HDHMR components, grooves, profiles and cut-to-size work.'],
                ['q' => 'Can you mark parts for assembly?', 'a' => 'Part numbering and organized production output can be planned for batch work, especially when the drawing set and assembly sequence are clear.'],
            ],
        ],
        'custom-cnc-projects' => [
            'title' => 'Custom CNC Projects',
            'h1' => 'Custom CNC Projects for Prototypes, Art, Furniture, Acrylic, ACP, WPC and Bespoke Manufacturing',
            'keyword' => 'Custom CNC Projects',
            'meta_description' => 'Custom CNC projects by Digi CNC Nagpur for prototypes, furniture, artwork, acrylic, ACP, WPC, engraving, wall panels, mandir designs and bespoke parts.',
            'image' => 'assets/images/banner-services-materials-clean.png',
            'summary' => 'Some CNC work does not fit a standard catalogue. Digi CNC supports custom projects where a client has a drawing, reference, idea, physical sample or problem statement and needs a manufacturing partner to convert it into a practical CNC output.',
            'applications' => ['Prototype development', 'Artist panels', 'Bespoke furniture', 'Display fixtures', 'Brand installations', 'Custom engraving'],
            'materials' => ['MDF', 'HDHMR', 'Wood', 'Acrylic', 'ACP', 'WPC', 'PVC', 'Plywood'],
            'differentiators' => ['Idea-to-output collaboration', 'Material and feasibility review', 'Prototype-friendly process', 'Custom business and homeowner support'],
            'faqs' => [
                ['q' => 'Can I bring only a reference photo?', 'a' => 'Yes. A reference photo can start the discussion. Digi CNC will still need dimensions, material preference and feasibility review before production.'],
                ['q' => 'Do you work with artists and product developers?', 'a' => 'Yes. Artists, prototype teams, furniture designers and product developers can use Digi CNC for custom panels, parts, models, forms and functional components.'],
                ['q' => 'Can custom CNC work be done in acrylic or ACP?', 'a' => 'Yes, subject to thickness, finish, design geometry and machining suitability. The file and material are reviewed before confirming production.'],
                ['q' => 'How do I start a custom CNC project?', 'a' => 'Send the drawing, reference image, dimensions, material, quantity and timeline by WhatsApp or the inquiry form. The team will review and guide the next step.'],
            ],
        ],
    ],
    'location_pages' => [
        'cnc-cutting-nagpur' => [
            'title' => 'CNC Cutting Nagpur',
            'h1' => 'CNC Cutting in Nagpur for Architects, Interior Designers, Furniture Teams and Homeowners',
            'keyword' => 'CNC Cutting Nagpur',
            'meta_description' => 'Looking for CNC cutting in Nagpur? Digi CNC provides 2D cutting, 3D carving, jali, MDF, HDHMR, acrylic, ACP, WPC and custom CNC manufacturing.',
            'image' => 'assets/images/hero-slider-jali-cnc-clean.png',
            'faqs' => [
                ['q' => 'Where is Digi CNC located?', 'a' => 'Digi CNC serves customers from Nagpur, Maharashtra and supports nearby project requirements based on scope, material and schedule.'],
                ['q' => 'Can Nagpur homeowners order CNC jali or mandir panels?', 'a' => 'Yes. Homeowners can order custom jali, mandir panels, wall panels, furniture details and decorative CNC elements after sharing dimensions and design references.'],
                ['q' => 'Do you work with contractors?', 'a' => 'Yes. Digi CNC regularly supports furniture contractors, interior execution teams and commercial project vendors with CNC-ready components.'],
            ],
        ],
        'cnc-cutting-maharashtra' => [
            'title' => 'CNC Cutting Maharashtra',
            'h1' => 'CNC Cutting Services for Maharashtra Projects from Digi CNC Nagpur',
            'keyword' => 'CNC Cutting Maharashtra',
            'meta_description' => 'Digi CNC supports CNC cutting and carving projects across Maharashtra for architects, interiors, furniture, prototypes, jali panels and custom manufacturing.',
            'image' => 'assets/images/hero-slider-components-prototype-clean.png',
            'faqs' => [
                ['q' => 'Can Digi CNC support projects outside Nagpur?', 'a' => 'Yes. Projects across Maharashtra can be discussed depending on file readiness, material, quantity, packaging and logistics.'],
                ['q' => 'Do you manufacture for designers in other cities?', 'a' => 'Yes. Architects and interior designers can share drawings remotely and coordinate production with Digi CNC for suitable CNC projects.'],
                ['q' => 'Can parts be packed for transport?', 'a' => 'Packaging and dispatch support depends on component size, fragility, finish and project scope. This is confirmed before production.'],
            ],
        ],
    ],
    'gallery' => [
        ['category' => '2D CNC Cutting', 'title' => 'Nested furniture components in MDF and plywood', 'image' => 'assets/images/hero-slider-components-prototype-clean.png', 'alt' => '2D CNC cutting in Nagpur for furniture components by Digi CNC'],
        ['category' => '3D CNC Carving', 'title' => 'Luxury carved wooden wall relief panel', 'image' => 'assets/images/portfolio-3d-carving.png', 'alt' => '3D CNC carving Nagpur decorative wooden relief panel'],
        ['category' => 'Parametric Designs', 'title' => 'Parametric rib wall for commercial interiors', 'image' => 'assets/images/hero-slider-parametric-wall-clean.png', 'alt' => 'Parametric design manufacturing Nagpur CNC rib wall'],
        ['category' => 'Jali Designs', 'title' => 'CNC router cutting an intricate MDF jali panel', 'image' => 'assets/images/hero-slider-jali-cnc-clean.png', 'alt' => 'Decorative jali cutting Nagpur MDF CNC jali panel'],
        ['category' => 'Furniture Components', 'title' => 'Ready-to-assemble CNC cut furniture parts', 'image' => 'assets/images/hero-slider-components-prototype-clean.png', 'alt' => 'CNC cut furniture components Nagpur by Digi CNC'],
        ['category' => 'Mandir Designs', 'title' => 'CNC mandir panel and ornate cutwork details', 'image' => 'assets/images/portfolio-jali-mandir.png', 'alt' => 'CNC mandir designs Nagpur decorative MDF HDHMR panels'],
        ['category' => 'Custom Projects', 'title' => 'Custom prototype and industrial sheet cutting work', 'image' => 'assets/images/banner-services-materials-clean.png', 'alt' => 'Custom CNC projects Nagpur prototype manufacturing by Digi CNC'],
        ['category' => '2D CNC Cutting', 'title' => 'CNC spindle cutting decorative board patterns', 'image' => 'assets/images/banner-about-process-clean.png', 'alt' => 'CNC cutting process in Nagpur for MDF and HDHMR panels'],
        ['category' => 'Custom Projects', 'title' => 'Mixed-material CNC samples for acrylic ACP WPC and plywood', 'image' => 'assets/images/banner-services-materials-clean.png', 'alt' => 'Acrylic ACP WPC plywood CNC cutting samples in Nagpur'],
    ],
    'testimonials' => [
        ['name' => 'Interior Design Studio, Nagpur', 'role' => 'Commercial Interiors', 'quote' => 'Digi CNC understood our drawings quickly and delivered clean jali panels with consistent finish. The communication was practical and production-focused.'],
        ['name' => 'Furniture Contractor', 'role' => 'Modular Furniture', 'quote' => 'For repeat components, accuracy matters. Their CNC cutting helped us reduce manual correction work and keep the site schedule under control.'],
        ['name' => 'Residential Client', 'role' => 'Mandir and Wall Panel', 'quote' => 'The team guided us on material and pattern strength before cutting. The final panels looked premium after finishing and installation.'],
    ],
    'blogs' => [
        [
            'title' => 'How to Prepare a Drawing for CNC Cutting',
            'slug' => 'how-to-prepare-a-drawing-for-cnc-cutting',
            'category' => 'CNC Guides',
            'image' => 'assets/images/banner-about-process-clean.png',
            'excerpt' => 'A practical guide for architects, contractors and homeowners who want faster CNC quotations and cleaner production output.',
            'content' => '<p>A good CNC result begins before the machine starts. Drawings should have correct dimensions, closed profiles, clear material thickness, quantity notes and finish expectations. For jali, web thickness and inside corner behavior should be checked before cutting. For furniture components, nesting, grain direction, hardware references and assembly labels can reduce confusion during production.</p><p>When sending a file to Digi CNC, include the use case, material, quantity, timeline and any site limitations. If the file has been exported from design software, avoid duplicate overlapping curves and tiny broken segments. Clean files help the team quote faster and machine more accurately.</p>',
            'published_at' => '2026-01-12',
        ],
        [
            'title' => 'MDF vs HDHMR for CNC Interior Projects',
            'slug' => 'mdf-vs-hdhmr-for-cnc-interior-projects',
            'category' => 'Materials',
            'image' => 'assets/images/hero-slider-components-prototype-clean.png',
            'excerpt' => 'Understand when to choose MDF and when HDHMR makes more sense for jali, furniture, kitchens, wardrobes and decorative panels.',
            'content' => '<p>MDF is widely used for painted decorative panels, carved features and cost-effective interior CNC work because it machines consistently. HDHMR is denser and better suited for areas where moisture resistance and durability matter, such as kitchens, wardrobes and heavy-use furniture components. The right choice depends on budget, finish, environment and design detail.</p><p>For delicate jali, panel strength and pattern thickness matter as much as the board type. Digi CNC reviews these details before machining so the final product is both attractive and practical.</p>',
            'published_at' => '2026-02-18',
        ],
        [
            'title' => 'Why Parametric CNC Panels Need Manufacturing Planning',
            'slug' => 'why-parametric-cnc-panels-need-manufacturing-planning',
            'category' => 'Parametric Design',
            'image' => 'assets/images/hero-slider-parametric-wall-clean.png',
            'excerpt' => 'Parametric design looks digital, but successful installation depends on numbering, tolerances, material behavior and assembly logic.',
            'content' => '<p>Parametric projects often include many unique parts. Without a manufacturing plan, beautiful geometry can become difficult to cut, pack and assemble. Part numbering, sheet optimization, slot tolerance, thickness consistency and installation sequence must be considered early. A sample panel is often the best way to verify scale and fit.</p><p>Digi CNC helps design teams convert parametric intent into components that can be machined, organized and installed with fewer surprises.</p>',
            'published_at' => '2026-03-09',
        ],
    ],
    'faqs' => [
        'home' => [
            ['q' => 'What does Digi CNC manufacture?', 'a' => 'Digi CNC manufactures 2D CNC cut parts, 3D carved panels, decorative jali, MDF and HDHMR components, parametric interiors, furniture parts, engraving, mandir designs and custom CNC projects.'],
            ['q' => 'Do you work with architects and interior designers?', 'a' => 'Yes. Digi CNC works with architects, interior designers, contractors and project teams that need production-ready CNC components from drawings, references or custom design briefs.'],
            ['q' => 'Can homeowners order a single custom project?', 'a' => 'Yes. Homeowners can order custom mandir panels, jali, wall panels, decorative elements and furniture parts after sharing dimensions, material preference and design references.'],
            ['q' => 'What is required for a quotation?', 'a' => 'Send dimensions, material, thickness, quantity, design file or reference image, finish requirement, timeline and location details. Clear input helps provide faster and more accurate guidance.'],
        ],
        'contact' => [
            ['q' => 'What is the fastest way to contact Digi CNC?', 'a' => 'Call or WhatsApp +91 9766653376 for urgent project discussions, file sharing and quick feasibility checks.'],
            ['q' => 'Can I send files on WhatsApp?', 'a' => 'Yes. You can send reference images, PDFs and drawings on WhatsApp. For production files, email or a file-sharing link may be better for larger attachments.'],
            ['q' => 'What information should I provide for an accurate CNC quotation?', 'a' => 'For the fastest and most accurate quotation, share material type, thickness, dimensions, quantity, design files or reference images, finishing requirements and expected timeline. Detailed project information helps Digi CNC review feasibility and provide more precise pricing guidance.'],
            ['q' => 'Do I need a CAD file before contacting Digi CNC?', 'a' => 'No. If a CAD file is not available, you can share sketches, reference images, dimensions or project requirements. Digi CNC can review the concept and guide the next steps for manufacturing.']
        ],
    ],
    'seo' => [
        'home' => [
            'title' => 'Digi CNC Nagpur | 2D & 3D CNC Cutting, Carving, Jali & Parametric Manufacturing',
            'description' => 'Digi CNC Nagpur provides 2D CNC cutting, 3D CNC carving, decorative jali, MDF, HDHMR, parametric design, furniture components and custom CNC projects.',
            'keywords' => 'CNC Cutting Service in Nagpur, 3D CNC Carving Nagpur, 2D CNC Cutting Nagpur, Parametric Design Nagpur, Decorative Jali Cutting Nagpur',
        ],
        'about' => [
            'title' => 'About Digi CNC Nagpur | Founder, CNC Manufacturing Process & Quality',
            'description' => 'Learn about Digi CNC, founded by Mr. Krunal Patel in Nagpur, offering precision CNC cutting, carving, jali, furniture components and custom manufacturing.',
            'keywords' => 'Digi CNC Nagpur, CNC manufacturer Nagpur, Krunal Patel CNC',
        ],
        'services' => [
            'title' => 'CNC Services in Nagpur | 2D Cutting, 3D Carving, Jali, MDF, HDHMR',
            'description' => 'Explore Digi CNC services including 2D CNC cutting, 3D carving, parametric manufacturing, MDF, HDHMR, acrylic, ACP, WPC, jali and custom CNC projects.',
            'keywords' => 'CNC Router Services, CNC Design Services, MDF CNC Cutting, HDHMR CNC Cutting',
        ],
        'gallery' => [
            'title' => 'CNC Gallery Nagpur | Jali, Carving, Furniture Components & Parametric Panels',
            'description' => 'View Digi CNC project categories including 2D cutting, 3D carving, parametric designs, jali, furniture components, mandir designs and custom projects.',
            'keywords' => 'CNC gallery Nagpur, jali cutting gallery, CNC carving portfolio',
        ],
        'blog' => [
            'title' => 'CNC Blog | Design, Materials, Manufacturing Tips by Digi CNC Nagpur',
            'description' => 'Read CNC cutting guides, material comparisons, jali planning tips, parametric design manufacturing insights and project preparation advice.',
            'keywords' => 'CNC blog Nagpur, CNC cutting guide, MDF HDHMR CNC',
        ],
        'contact' => [
            'title' => 'Contact Digi CNC Nagpur | Call +91 9766653376 for CNC Cutting & Carving',
            'description' => 'Contact Digi CNC Nagpur for 2D CNC cutting, 3D carving, jali, MDF, HDHMR, furniture components, prototypes and custom CNC project quotations.',
            'keywords' => 'Contact CNC Cutting Nagpur, Digi CNC phone number, CNC quotation Nagpur',
        ],
    ],
];
